### ISSUE TITLE
esto esta vacio kike

### ISSUE THREAD

**Issue by josesabor** [titicuevas/Entorno#1]
1. No me parece bien que este vacio
`viva el betis`

**Comment by titicuevas** [comment]
Que dices gilipollas?

**Comment by josesabor** [comment]
### *Muy mal kike*

**Comment by titicuevas** [comment]
Pues comeme los huevos desgraciado

**Comment by josesabor** [comment]
### Muy mal compañerismo kike, ya no entras en `*atsistemas*`

**Comment by titicuevas** [comment]
Tengo pelo eso es uno de los requisitos

**Comment by josesabor** [comment]
# A FRANBARGAR SE LO VOY A DECIR

**Comment by titicuevas** [comment]
Quien es FRAN###

**Comment by titicuevas** [comment]
### ### ### ### ### ### ### ### ###

**Comment by josesabor** [comment]
haber si aprendemos a usar markdown
