### ISSUE TITLE
No entiendo el repositorio

### ISSUE THREAD

**Issue by alfredobp** [titicuevas/Entorno#2]
Hola, ¿Pues especificar de que va el repositorio?

**Comment by titicuevas** [comment]
Si lo está explicando y no sabe ni lo que hace

**Comment by alfredobp** [comment]
haz un var_dump, eso siempre funciona.

**Comment by jujerez** [comment]
alias var_dump = rm -rf

**Comment by titicuevas** [comment]
Este tio no sabe ni lo que explica

**Comment by alfredobp** [comment]
```
public function setCuantas($cuantas)
    {
        $this->_cuantas = $cuantas;
    }

    public function getCuantas()
    {
        if ($this->_cuantas === null) {
            $this->_cuantas = Peliculas::find()
                ->where(['genero_id' => $this->id])
                ->count();
        }

        return $this->_cuantas;
    }
```

**Comment by jujerez** [comment]
public function setCuantas($cuantas)
    {
        $this->_cuantas = $cuantas;
    }

    public function getCuantas()
    {
        if ($this->_cuantas === null) {
            $this->getPeliculas()->count()
        }

        return $this->_cuantas;
    }
